export const DEBATE_INVITATION = 'Debate Invitation';
export const DEBATE_LEAVE = 'Debate Leave';
export const DEBATE_NEW_MESSAGE = 'Debate New Message';
export const DEBATE_UPDATE_MESSAGE = 'Debate Update Message';

export const MESSAGE_TYPES = {
    DEBATE_NOTIFICATION: 'DEBATE_NOTIFICATION',
    CONVERT_MSG_TO_BOT_MSG_RESPONSE: 'CONVERT_MSG_TO_BOT_MSG_RESPONSE',
    UPDATE_DEBATE_MESSAGE_NOTIFICATION: 'UPDATE_DEBATE_MESSAGE_NOTIFICATION',
}